# Generated by Django 6.0.6 on 2026-06-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_address_order_city_order_full_name_order_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('upi', 'UPI'), ('card', 'Card')], default='cod', max_length=20),
        ),
    ]
